### SparklyRGT Template: Baseline and Acquisition Analysis 

**Requirements**
* The data must be an excel file from MEDPC2XL (trial by trial data) 
* The data, sparklyRGT.py file, and this notebook must all be in the same folder

**Getting started: Please make a copy of this (sparklyRGT_template_2) for each analysis**
- Refer to sparklyRGT_documentation for function information
- Note: depending on your analysis, you will only have to complete certain sections of the sparklyRGT_documentation
- Note: feel free to create a personal template once you've become comfortable - this is just an example

In [1]:
import os
os.chdir('..')
import sparklyRGT as rgt 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
import scipy.stats as stats
pd.options.mode.chained_assignment = None
pd.set_option('display.max_rows',100)

I am being executed!

***

# 1) Load data into Python

In [3]:
#remove the leading 'M' from the TF file subject numbers and convert to integer/float

In [4]:
#add header names from BH03 to other files so they can be concatenated properly

In [2]:
from os import walk
#data needs to be loaded in from OSF
#either download them from OSF and upload to github, or load in directly from OSF 

#OSF files are CSVs (except BH03 is xlsx) and load_multiple_data loads in excel files
#sparklyrgt.py needs to be edited so that either excel files or CSVs can be loaded in

path = '../sparklyRGT_tutorial/data/'
file_names = [f for f in walk(path)]

df = rgt.load_multiple_data(file_names, path, reset_sessions = False)

df.head()
df.to_csv('../sparklyRGT_tutorial/output.csv')

IsADirectoryError: [Errno 21] Is a directory: '../sparklyRGT_tutorial/data/.ipynb_checkpoints'

In [28]:

# set reset_sessions = false
# run all exclusions
# add:
# check if there's any rats that have less than 20 session numbers -- exclude them

# figure out which file is printing -- order of file 
# then run reset sections --> set session number 1 -> n for each subject number
# rats will have at least 20 sessions (after exclusion above)
# write function where it checks whether each subject has 1-20 session number

# save a csv of session 18-20 (after reset), 2 files, cue and classic


def check_sessions(df): ##checks that the 'Session' column has correct, and non-missing session numbers
    pd.set_option('display.max_rows', None) ##otherwise it will ... the middle rows (only give the head and tail)
    print(df.groupby(['Subject','StartDate','Session'])['Trial'].max())
    pd.set_option('display.max_rows',df.Subject.max()) ##this sets the number of displayed rows to the number of subjects

In [25]:
from os import listdir
path = '../sparklyRGT_tutorial/'
file_names = ['output.csv']

df = rgt.load_data(file_names, reset_sessions = False)
# df = df.drop(df.columns[[0]], axis=1)

task_list = df.groupby(['MSN'])['Subject'].unique()
#print(task_list)
check_sessions(df)

<ipython-input-25-053730905391>:5: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  df = rgt.load_data(file_names, reset_sessions = False)

MSN
RGT_5csrtTrain                                                 [726]
RGT_ClassicA       [209, 210, 211, 212, 225, 226, 227, 228, 509, ...
RGT_ClassicB       [213, 214, 215, 216, 229, 230, 231, 232, 513, ...
RGT_FC_ClassicA                                 [611, 627, 709, 726]
RGT_FC_ClassicB                                      [615, 631, 632]
RIGT_ClassicA                              [901, 902, 916, 911, 912]
RIGT_ClassicB                                        [915, 909, 910]
rGT_5csrtTrain                                            [607, 623]
rGT_A-cue          [173, 174, 165, 166, 167, 168, 185, 186, 177, ...
rGT_A-cue-FC2                                           [1312, 1304]
rGT_B-cue          [175, 169, 170, 171, 172, 187, 188, 181, 182, ...
rGT_B-cue-FC                                            [1307, 1308]
rGT_ClassicA       [201, 202, 203, 204, 217, 218, 219, 220, 233, ...
rGT_ClassicB       [205, 206, 207, 208, 221, 222, 223, 224, 237, ...
rGT_FC_ClassicA             [701, 702, 703, 704, 717, 718, 719, 720]
rGT_FC_ClassicB    [608, 624, 623, 607, 705, 706, 707, 708, 721, ...
Name: Subject, dtype: object

In [20]:
subjects = df.drop_duplicates(subset=['Subject', 'Session'])
subjects_n = subjects[['Subject', 'Session']]
zero_session = []
for index, row in subjects_n.iterrows():
    if row["Session"] == 0:
        zero_session.append(row["Subject"])
        
# drop subjects that had a 0 session
df = rgt.drop_subjects(df, zero_session)

## Data cleaning

### Check session numbers for each rat and drop subjects

In [3]:
#missing data

#we need to only take rats that have consecutive sessions from 1 to 5
#some rats will be missing sessions and need to be excluded

# removes subjects where the first 5 sessions are not consecutive
subjects = df.drop_duplicates(subset=['Subject', 'Session'])
subjects_n = subjects[['Subject', 'Session']]
# sort sessions in ascending order to check for consecutive sessions
subjects_n = subjects_n.sort_values(by=['Subject', 'Session'])
# count number of subjects
n = subjects_n['Subject'].nunique()
drop_subs = []

i = 0
temp = subjects_n
# iterate through each subject and check if they have the first 5 sessions consecutive
while i < n:
    # look at first 5 rows from subject
    check_consec = temp.head()
    # get subject number
    num = check_consec['Subject'].iloc[0]
    # convert first 5 sessions into number list
    con_list = check_consec['Session'].tolist()
    # list -> int
    con_list = list(map(int, con_list))
    # check if list is not consecutive, if so, add to drop list
    if sorted(con_list) != list(range(min(con_list), max(con_list)+1)):
        drop_subs.append(num)
    i = i + 1
    # remove the subject from the list, move to next subject
    temp = temp[temp.Subject != num]
print(drop_subs)
# drop subjects that did not have consecutive sessions (5)
df2 = rgt.drop_subjects(df, drop_subs)
df2

[165, 166, 167, 168, 169, 170, 171, 172, 303, 304, 305, 306, 309, 310, 311, 312, 313, 314, 315, 316, 525, 526, 527, 528, 707, 717, 723, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 826, 1025, 1026, 1027, 1029, 1030, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1218, 1418, 1422, 1426]

,MSN,StartDate,StartTime,Subject,Group,Box,Experiment,Comment,Session,Trial,...,Pun_Persev_H5,Pun_HeadEntry,Pun_Dur,Premature_Resp,Premature_Hole,Rew_Persev_H1,Rew_Persev_H2,Rew_Persev_H3,Rew_Persev_H4,Rew_Persev_H5
0,rGT_A-cue,01/23/16,8:13:19,173,0.0,1,0.0,NaN,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,rGT_A-cue,01/23/16,8:13:19,173,0.0,1,0.0,NaN,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,rGT_A-cue,01/23/16,8:13:19,173,0.0,1,0.0,NaN,1.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,rGT_A-cue,01/23/16,8:13:19,173,0.0,1,0.0,NaN,1.0,4.0,...,2.0,1.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,rGT_A-cue,01/23/16,8:13:19,173,0.0,1,0.0,NaN,1.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564088,rGT_B-cue,11/15/18,16:10:57,1508,0.0,8,GB01,NaN,40.0,51.0,...,1.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
564089,rGT_B-cue,11/15/18,16:10:57,1508,0.0,8,GB01,NaN,40.0,52.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
564090,rGT_B-cue,11/15/18,16:10:57,1508,0.0,8,GB01,NaN,40.0,53.0,...,0.0,4.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
564091,rGT_B-cue,11/15/18,16:10:57,1508,0.0,8,GB01,NaN,40.0,54.0,...,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
564092,rGT_B-cue,11/15/18,16:10:57,1508,0.0,8,GB01,NaN,40.0,55.1,...,0.0,0.0,0.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0

In [4]:
#check if there are any subjects that were run on more than one task version (including 5CSRT, FC)

#to display all the task names in the dataframe:
# df2.MSN.unique()
# drop duplicate rows
tasks = df2.drop_duplicates(subset=['Subject', 'MSN'])
# look at subjects and tasks
tasks_n = tasks[['Subject', 'MSN']]
# sort by subject number
tasks_n = tasks_n.sort_values(by=['Subject'])
# find subject numbers that appear more than once in list
tasks_n_dup = tasks_n[tasks_n.duplicated(['Subject'], keep=False)]
tasks_n_dup = tasks_n_dup.Subject.unique()
duplicate_tasks = []
# iterate through subjects with more than 1 task and save them to list
for i in tasks_n_dup:
    duplicate_tasks.append(i)
print(duplicate_tasks)
#drop any subjects that were run on more than one task 
final_subjects = rgt.drop_subjects(df2, duplicate_tasks)

[708, 711, 715, 724, 727, 731, 732, 1404, 1407, 1408, 1412, 1419, 1420, 1424, 1425, 1427, 1429, 1430]

In [5]:
final_subjects.to_csv('sockeye_data.csv')

In [ ]:
# split the dataframe by cued and classic rats, and save them as two separate CSVs (both with column headers)

#all cued tasks will have 'cue' in the MSN (A and B version)
#all classic tasks should have 'Classic' (A and B) - either rGT or RGT 

#upload to sparklyRGT/data